--- 
- 
  apt: 
    name: dnsmasq
    state: latest
  name: "Update to latest DHCP"
- 
  copy: 
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  name: "Copy the DHCP config"
  notify:
    - "restart dnsmasq"
- name: deploy resol.conf template
  template:
    src: roles/dnsmasq/templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

